---
# tasks file for apache
  - name: Install httpd
    yum:
        name: "{{package_name}}"
        state: present

  - name: Start the httpd Deamon
    systemd:
        name: "{{package_name}}"
        state: started
        enabled: yes
    
  - name: Copy index file to the target
    copy:
        src: index.html
        dest: /var/www/html/index.html
    notify: Restart Apache
