---
- hosts: db
  become: yes
  gather_facts: no

  tasks:
    - name: Update the system
      yum: 
        name: '*'
        state: latest
      tags: 
        - update

    - name: Install httpd
      yum:
        name: httpd
        state: present
      tags: 
        - install

    - name: Start the httpd Deamon
      systemd:
        name: httpd
        state: started
        enabled: yes
      tags: 
        - start

    - name: Copy index file to the target
      copy:
        src: index.html
        dest: /var/www/html/index.html
      tags:
        - copy_file
      notify: 
        - Restart Apache
 
  handlers:
    - name: Restart Apache 
      systemd:
        name: httpd
        state: restarted
    


    
          





