
---
- hosts: all
  become: true
  gather_facts: yes
  ignore_errors: true
  vars:
    user_name: francoise2024
    group_name: devops
  vars_files:
    - variables.yml
    
  tasks:
    - name: Check the time
      command: datekkkk
       when: ansible_distribution -- "francoise" or ansible_processor_nproc -- 2
    - name: create user francoise
      user:
        name: "{{user_name}}"
        comment: francoise Admin
    - name: create group
      group:
        name: "{{group_name}}"
        state: present
    - name: Install package
      package:
        name: "{{pkg_name}}"
        state: present  